version: '3'
services:
  web:
    build: .
    volumes:
    - .:/code
    ports:
    - "3000:3000"
    depends_on:
    - db
    environment:
      DB_HOST: db
      DB_NAME: states_countries_database
      DB_USER: postgres
  db:
    image: postgres